apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: simple-weather
  name: simple-weather
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30100
  selector:
    app: simple-weather
  type: NodePort
status:
  loadBalancer: {}
